version: '3.7'
services:
  Proyecto-microservicio01:
    container_name: "Proyecto-microservicio01"
    image: juangutierrezr/proyecto-microservicio:v1
    build:
      context: .
    ports:
      - "5001:4006"
    networks:
      - efasis-2-web2_Proyecto
    environment:
     CONTAINER_HOST: Proyecto-microservicio01

  Proyecto-microservicio02:
    container_name: "Proyecto-microservicio02"
    image: juangutierrezr/proyecto-microservicio:v1
    build:
      context: .
    ports:
      - "5002:4006"
    networks:
      - efasis-2-web2_Proyecto
    environment:
     CONTAINER_HOST: Proyecto-microservicio02

  load-balancer:
    container_name: "load-balancer"
    image: load-balancer:v1
    build:
      context: ./load-balancer
    ports:
      - "8082:80"
     
    networks:
      - efasis-2-web2_Proyecto
    depends_on:
      - Proyecto-microservicio01
      - Proyecto-microservicio02
    restart: always

volumes:
  mongodb:
networks:
  efasis-2-web2_Proyecto:
    external: true
