version: '3.7'
services:
  proyecto-microservicio01:
    container_name: "proyecto-microservicio01"
    image: juangutierrezr/proyecto-microservicio:v1
    ports:
      - "5001:4006"
    networks:
      - proyecto
    environment:
      CONTAINER_HOST: proyecto-microservicio01
    depends_on:
      - proyecto-database

  proyecto-microservicio02:
    container_name: "proyecto-microservicio02"
    image: juangutierrezr/proyecto-microservicio:v1
    ports:
      - "5002:4006"
    networks:
      - proyecto
    environment:
      CONTAINER_HOST: proyecto-microservicio02
    depends_on:
      - proyecto-database

  proyecto-database:
    container_name: "proyecto-database"
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - proyecto
    volumes:
      - mongodb:/data/db

  load-balancer:
    container_name: "load-balancer"
    image: juangutierrezr/load-balancer:v1
    #build:
    #  context: ./load-balancer
    ports:
      - "8082:80"

    networks:
      - proyecto
    depends_on:
      - proyecto-microservicio01
      - proyecto-microservicio02
    restart: always

volumes:
  mongodb:
networks:
  proyecto:
    driver: bridge
    ##networks:
    ##efasis-2-web2_proyecto:
    ##external: true
